default:
    trainer: ppo
    batch_size: 128
    beta: 1.0e-2
    buffer_size: 1280
    epsilon: 0.1
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 10.0e4
    memory_size: 256
    normalize: false
    num_epoch: 5
    num_layers: 3
    time_horizon: 512
    sequence_length: 128
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals: 
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 1.0
            gamma: 0.99
            encoding_size: 256
    
