default:
    trainer: ppo
    batch_size: 16
    beta: 1.0e-2
    buffer_size: 160
    epsilon: 0.15
    hidden_units: 512
    lambd: 0.90
    learning_rate: 1.0e-4
    max_steps: 25.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals: 
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 0.01
            gamma: 0.99
            encoding_size: 256
