default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 512
    lambd: 0.90
    learning_rate: 1.0e-4
    max_steps: 20.0e4
    memory_size: 256
    normalize: true
    num_epoch: 3
    num_layers: 3
    time_horizon: 128
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals: 
        extrinsic:
            strength: 1.0
            gamma: 0.99
        curiosity:
            strength: 1.0
            gamma: 0.99
            encoding_size: 256
    
